version: '3.8'
services:
  webapp:
    build: .
    ports:
      - "3001:3001"
      - "5001:5001"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
